name: todo_mvc
version: 0.0.9
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: Todo.Mvc is a demo, done with Dartling, of the TodoMVC project. Based on TodoMVC in Dart. Dartling is a domain model framework for web application prototypes. A new dartling project is copied and adapted from dartling_skeleton.
homepage: http://ondart.me/
dependencies:
  browser: any
  dartling:
    git: git://github.com/dzenanr/dartling.git
  dartling_default_app:
    git: git://github.com/dzenanr/dartling_default_app.git
