name: todo_mvc
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: http://ondart.me/
version: 0.0.2
description: >
  Todo.Mvc is a demo, done with Dartling, of the TodoMVC project.
  Based on TodoMVC in Dart.
  Dartling is a domain model framework for web application prototypes.
  A new dartling project is copied and adapted from dartling_skeleton.
dependencies:
  browser: any
  dartling:
    git: git://github.com/dzenanr/dartling.git
  dartling_default_app:
    git: git://github.com/dzenanr/dartling_default_app.git